2025-06-07 14:24:22.353  INFO 22266 --- [           main] com.aciworldwide.aclabs22.Aclabs22Application : Starting Aclabs22Application using Java 24 on Darios-MacBook-Pro.local with PID 22266 (/Users/dariofriskan/Documents/ACI-LigaACLabs2023-REST/target/classes started by dariofriskan in /Users/dariofriskan/Documents/ACI-LigaACLabs2023-REST)
2025-06-07 14:24:22.356 DEBUG 22266 --- [           main] com.aciworldwide.aclabs22.Aclabs22Application : Running with Spring Boot v2.6.3, Spring v5.3.15
2025-06-07 14:24:22.356  INFO 22266 --- [           main] com.aciworldwide.aclabs22.Aclabs22Application : No active profile set, falling back to default profiles: default
2025-06-07 14:24:22.823 DEBUG 22266 --- [           main] com.aciworldwide.aclabs22.utils.JWTAuthenticationFilter : Filter 'JWTAuthenticationFilter' configured for use
2025-06-07 14:24:23.706  INFO 22266 --- [           main] com.aciworldwide.aclabs22.Aclabs22Application : Started Aclabs22Application in 1.456 seconds (JVM running for 1.998)
2025-06-07 14:24:33.987  INFO 22266 --- [nio-8080-exec-1] com.aciworldwide.aclabs22.controllers.LoginController : Processing login: admin with pwd admin
2025-06-07 14:24:34.036  INFO 22266 --- [nio-8080-exec-1] com.aciworldwide.aclabs22.services.UserService : com.aciworldwide.aclabs22.entities.UserModel@35e9bf04
2025-06-07 14:47:46.672  INFO 22569 --- [           main] com.aciworldwide.aclabs22.Aclabs22Application : Starting Aclabs22Application using Java 24 on Darios-MacBook-Pro.local with PID 22569 (/Users/dariofriskan/Documents/ACI-LigaACLabs2023-REST/target/classes started by dariofriskan in /Users/dariofriskan/Documents/ACI-LigaACLabs2023-REST)
2025-06-07 14:47:46.674 DEBUG 22569 --- [           main] com.aciworldwide.aclabs22.Aclabs22Application : Running with Spring Boot v2.6.3, Spring v5.3.15
2025-06-07 14:47:46.674  INFO 22569 --- [           main] com.aciworldwide.aclabs22.Aclabs22Application : No active profile set, falling back to default profiles: default
2025-06-07 14:47:47.130 DEBUG 22569 --- [           main] com.aciworldwide.aclabs22.utils.JWTAuthenticationFilter : Filter 'JWTAuthenticationFilter' configured for use
2025-06-07 14:47:48.008  INFO 22569 --- [           main] com.aciworldwide.aclabs22.Aclabs22Application : Started Aclabs22Application in 1.451 seconds (JVM running for 1.894)
2025-06-07 14:47:58.292 ERROR 22569 --- [nio-8080-exec-1] com.aciworldwide.aclabs22.services.AnomalyService : Python script exited with code 1
2025-06-07 14:47:58.292 ERROR 22569 --- [nio-8080-exec-1] com.aciworldwide.aclabs22.services.AnomalyService : Output/Error: Traceback (most recent call last):  File "/Users/dariofriskan/Documents/ACI-LigaACLabs2023-REST/src/model/predict.py", line 7, in <module>    model = joblib.load('model.pkl')            ^^^^^^^^^^^^^^^^^^^^^^^^  File "/opt/anaconda3/lib/python3.12/site-packages/joblib/numpy_pickle.py", line 650, in load    with open(filename, 'rb') as f:         ^^^^^^^^^^^^^^^^^^^^FileNotFoundError: [Errno 2] No such file or directory: 'model.pkl'
2025-06-07 14:48:57.307 ERROR 22569 --- [nio-8080-exec-2] com.aciworldwide.aclabs22.services.AnomalyService : Python script exited with code 1
2025-06-07 14:48:57.308 ERROR 22569 --- [nio-8080-exec-2] com.aciworldwide.aclabs22.services.AnomalyService : Output/Error: Traceback (most recent call last):  File "/Users/dariofriskan/Documents/ACI-LigaACLabs2023-REST/src/model/predict.py", line 7, in <module>    model = joblib.load('model.pkl')            ^^^^^^^^^^^^^^^^^^^^^^^^  File "/opt/anaconda3/lib/python3.12/site-packages/joblib/numpy_pickle.py", line 650, in load    with open(filename, 'rb') as f:         ^^^^^^^^^^^^^^^^^^^^FileNotFoundError: [Errno 2] No such file or directory: 'model.pkl'
2025-06-07 14:49:12.368 ERROR 22569 --- [nio-8080-exec-3] com.aciworldwide.aclabs22.services.AnomalyService : Python script exited with code 1
2025-06-07 14:49:12.368 ERROR 22569 --- [nio-8080-exec-3] com.aciworldwide.aclabs22.services.AnomalyService : Output/Error: Traceback (most recent call last):  File "/Users/dariofriskan/Documents/ACI-LigaACLabs2023-REST/src/model/predict.py", line 7, in <module>    model = joblib.load('model.pkl')            ^^^^^^^^^^^^^^^^^^^^^^^^  File "/opt/anaconda3/lib/python3.12/site-packages/joblib/numpy_pickle.py", line 650, in load    with open(filename, 'rb') as f:         ^^^^^^^^^^^^^^^^^^^^FileNotFoundError: [Errno 2] No such file or directory: 'model.pkl'
2025-06-07 14:51:57.593  INFO 22569 --- [nio-8080-exec-1] com.aciworldwide.aclabs22.controllers.TransactionController : Received transaction request: TransactionDTO(cardNumber=1234567812345670, amount=42500.0, timestamp=2025-06-07 14:51:57.57)
2025-06-07 14:51:57.605  INFO 22569 --- [nio-8080-exec-1] com.aciworldwide.aclabs22.helpers.ValidationHelper : Validation succeeded with status: APPROVED and message: Transaction approved
2025-06-07 14:51:57.630  INFO 22569 --- [nio-8080-exec-1] com.aciworldwide.aclabs22.services.TransactionService : Transaction saved: 82
2025-06-07 14:52:01.779 ERROR 22569 --- [nio-8080-exec-2] com.aciworldwide.aclabs22.services.AnomalyService : Python script exited with code 1
2025-06-07 14:52:01.779 ERROR 22569 --- [nio-8080-exec-2] com.aciworldwide.aclabs22.services.AnomalyService : Output/Error: Traceback (most recent call last):  File "/Users/dariofriskan/Documents/ACI-LigaACLabs2023-REST/src/model/predict.py", line 7, in <module>    model = joblib.load('model.pkl')            ^^^^^^^^^^^^^^^^^^^^^^^^  File "/opt/anaconda3/lib/python3.12/site-packages/joblib/numpy_pickle.py", line 650, in load    with open(filename, 'rb') as f:         ^^^^^^^^^^^^^^^^^^^^FileNotFoundError: [Errno 2] No such file or directory: 'model.pkl'
2025-06-07 14:52:08.817 ERROR 22569 --- [nio-8080-exec-3] com.aciworldwide.aclabs22.services.AnomalyService : Python script exited with code 1
2025-06-07 14:52:08.817 ERROR 22569 --- [nio-8080-exec-3] com.aciworldwide.aclabs22.services.AnomalyService : Output/Error: Traceback (most recent call last):  File "/Users/dariofriskan/Documents/ACI-LigaACLabs2023-REST/src/model/predict.py", line 7, in <module>    model = joblib.load('model.pkl')            ^^^^^^^^^^^^^^^^^^^^^^^^  File "/opt/anaconda3/lib/python3.12/site-packages/joblib/numpy_pickle.py", line 650, in load    with open(filename, 'rb') as f:         ^^^^^^^^^^^^^^^^^^^^FileNotFoundError: [Errno 2] No such file or directory: 'model.pkl'
2025-06-07 14:52:12.808 ERROR 22569 --- [nio-8080-exec-4] com.aciworldwide.aclabs22.services.AnomalyService : Python script exited with code 1
2025-06-07 14:52:12.808 ERROR 22569 --- [nio-8080-exec-4] com.aciworldwide.aclabs22.services.AnomalyService : Output/Error: Traceback (most recent call last):  File "/Users/dariofriskan/Documents/ACI-LigaACLabs2023-REST/src/model/predict.py", line 7, in <module>    model = joblib.load('model.pkl')            ^^^^^^^^^^^^^^^^^^^^^^^^  File "/opt/anaconda3/lib/python3.12/site-packages/joblib/numpy_pickle.py", line 650, in load    with open(filename, 'rb') as f:         ^^^^^^^^^^^^^^^^^^^^FileNotFoundError: [Errno 2] No such file or directory: 'model.pkl'
2025-06-07 14:55:07.106 ERROR 22569 --- [nio-8080-exec-5] com.aciworldwide.aclabs22.services.AnomalyService : Python script exited with code 1
2025-06-07 14:55:07.106 ERROR 22569 --- [nio-8080-exec-5] com.aciworldwide.aclabs22.services.AnomalyService : Output/Error: Traceback (most recent call last):  File "/Users/dariofriskan/Documents/ACI-LigaACLabs2023-REST/src/model/predict.py", line 7, in <module>    model = joblib.load('model.pkl')            ^^^^^^^^^^^^^^^^^^^^^^^^  File "/opt/anaconda3/lib/python3.12/site-packages/joblib/numpy_pickle.py", line 650, in load    with open(filename, 'rb') as f:         ^^^^^^^^^^^^^^^^^^^^FileNotFoundError: [Errno 2] No such file or directory: 'model.pkl'
2025-06-07 15:03:03.287  INFO 22569 --- [nio-8080-exec-5] com.aciworldwide.aclabs22.controllers.TransactionController : Received transaction request: TransactionDTO(cardNumber=1234, amount=7000.0, timestamp=2025-06-04 04:45:00.0)
2025-06-07 15:03:03.291 ERROR 22569 --- [nio-8080-exec-5] com.aciworldwide.aclabs22.helpers.ValidationHelper : Validation failed with status: INVALID_CARD_NUMBER_LENGTH and message: Invalid card number length
2025-06-07 15:03:03.291 ERROR 22569 --- [nio-8080-exec-5] com.aciworldwide.aclabs22.services.TransactionService : Transaction rejected by application. Bad Request: Invalid card number length
2025-06-07 15:03:32.579  INFO 22569 --- [nio-8080-exec-6] com.aciworldwide.aclabs22.controllers.TransactionController : Received transaction request: TransactionDTO(cardNumber=1234567812345670, amount=7000.0, timestamp=2025-06-04 04:45:00.0)
2025-06-07 15:03:32.583  INFO 22569 --- [nio-8080-exec-6] com.aciworldwide.aclabs22.helpers.ValidationHelper : Validation succeeded with status: APPROVED and message: Transaction approved
2025-06-07 15:03:32.626  INFO 22569 --- [nio-8080-exec-6] com.aciworldwide.aclabs22.services.TransactionService : Transaction saved: 83
2025-06-07 15:04:02.151 ERROR 22569 --- [nio-8080-exec-8] com.aciworldwide.aclabs22.services.AnomalyService : Python script exited with code 1
2025-06-07 15:04:02.151 ERROR 22569 --- [nio-8080-exec-8] com.aciworldwide.aclabs22.services.AnomalyService : Output/Error: Traceback (most recent call last):  File "/Users/dariofriskan/Documents/ACI-LigaACLabs2023-REST/src/model/predict.py", line 7, in <module>    model = joblib.load('model.pkl')            ^^^^^^^^^^^^^^^^^^^^^^^^  File "/opt/anaconda3/lib/python3.12/site-packages/joblib/numpy_pickle.py", line 650, in load    with open(filename, 'rb') as f:         ^^^^^^^^^^^^^^^^^^^^FileNotFoundError: [Errno 2] No such file or directory: 'model.pkl'
2025-06-07 15:04:55.020 ERROR 22569 --- [nio-8080-exec-9] com.aciworldwide.aclabs22.services.AnomalyService : Python script exited with code 1
2025-06-07 15:04:55.020 ERROR 22569 --- [nio-8080-exec-9] com.aciworldwide.aclabs22.services.AnomalyService : Output/Error: Traceback (most recent call last):  File "/Users/dariofriskan/Documents/ACI-LigaACLabs2023-REST/src/model/predict.py", line 7, in <module>    model = joblib.load('model.pkl')            ^^^^^^^^^^^^^^^^^^^^^^^^  File "/opt/anaconda3/lib/python3.12/site-packages/joblib/numpy_pickle.py", line 650, in load    with open(filename, 'rb') as f:         ^^^^^^^^^^^^^^^^^^^^FileNotFoundError: [Errno 2] No such file or directory: 'model.pkl'
2025-06-07 15:11:27.033 ERROR 22569 --- [nio-8080-exec-4] com.aciworldwide.aclabs22.services.AnomalyService : Python script exited with code 1
2025-06-07 15:11:27.034 ERROR 22569 --- [nio-8080-exec-4] com.aciworldwide.aclabs22.services.AnomalyService : Output/Error: Traceback (most recent call last):  File "/Users/dariofriskan/Documents/ACI-LigaACLabs2023-REST/src/model/predict.py", line 7, in <module>    model = joblib.load('model.pkl')            ^^^^^^^^^^^^^^^^^^^^^^^^  File "/opt/anaconda3/lib/python3.12/site-packages/joblib/numpy_pickle.py", line 650, in load    with open(filename, 'rb') as f:         ^^^^^^^^^^^^^^^^^^^^FileNotFoundError: [Errno 2] No such file or directory: 'model.pkl'
2025-06-07 15:11:36.501 ERROR 22569 --- [nio-8080-exec-5] com.aciworldwide.aclabs22.services.AnomalyService : Python script exited with code 1
2025-06-07 15:11:36.501 ERROR 22569 --- [nio-8080-exec-5] com.aciworldwide.aclabs22.services.AnomalyService : Output/Error: Traceback (most recent call last):  File "/Users/dariofriskan/Documents/ACI-LigaACLabs2023-REST/src/model/predict.py", line 7, in <module>    model = joblib.load('model.pkl')            ^^^^^^^^^^^^^^^^^^^^^^^^  File "/opt/anaconda3/lib/python3.12/site-packages/joblib/numpy_pickle.py", line 650, in load    with open(filename, 'rb') as f:         ^^^^^^^^^^^^^^^^^^^^FileNotFoundError: [Errno 2] No such file or directory: 'model.pkl'
2025-06-07 15:21:35.690  INFO 22935 --- [           main] com.aciworldwide.aclabs22.Aclabs22Application : Starting Aclabs22Application using Java 24 on Darios-MacBook-Pro.local with PID 22935 (/Users/dariofriskan/Documents/ACI-LigaACLabs2023-REST/target/classes started by dariofriskan in /Users/dariofriskan/Documents/ACI-LigaACLabs2023-REST)
2025-06-07 15:21:35.693 DEBUG 22935 --- [           main] com.aciworldwide.aclabs22.Aclabs22Application : Running with Spring Boot v2.6.3, Spring v5.3.15
2025-06-07 15:21:35.693  INFO 22935 --- [           main] com.aciworldwide.aclabs22.Aclabs22Application : No active profile set, falling back to default profiles: default
2025-06-07 15:21:36.161 DEBUG 22935 --- [           main] com.aciworldwide.aclabs22.utils.JWTAuthenticationFilter : Filter 'JWTAuthenticationFilter' configured for use
2025-06-07 15:21:36.962  INFO 22935 --- [           main] com.aciworldwide.aclabs22.Aclabs22Application : Started Aclabs22Application in 1.387 seconds (JVM running for 1.835)
2025-06-07 15:21:46.640 ERROR 22935 --- [nio-8080-exec-2] com.aciworldwide.aclabs22.services.AnomalyService : Python script exited with code 1
2025-06-07 15:21:46.640 ERROR 22935 --- [nio-8080-exec-2] com.aciworldwide.aclabs22.services.AnomalyService : Output/Error: Traceback (most recent call last):  File "/Users/dariofriskan/Documents/ACI-LigaACLabs2023-REST/src/model/predict.py", line 7, in <module>    model = joblib.load('model.pkl')            ^^^^^^^^^^^^^^^^^^^^^^^^  File "/opt/anaconda3/lib/python3.12/site-packages/joblib/numpy_pickle.py", line 650, in load    with open(filename, 'rb') as f:         ^^^^^^^^^^^^^^^^^^^^FileNotFoundError: [Errno 2] No such file or directory: 'model.pkl'
2025-06-07 15:26:53.452  INFO 23020 --- [           main] com.aciworldwide.aclabs22.Aclabs22Application : Starting Aclabs22Application using Java 24 on Darios-MacBook-Pro.local with PID 23020 (/Users/dariofriskan/Documents/ACI-LigaACLabs2023-REST/target/classes started by dariofriskan in /Users/dariofriskan/Documents/ACI-LigaACLabs2023-REST)
2025-06-07 15:26:53.456 DEBUG 23020 --- [           main] com.aciworldwide.aclabs22.Aclabs22Application : Running with Spring Boot v2.6.3, Spring v5.3.15
2025-06-07 15:26:53.456  INFO 23020 --- [           main] com.aciworldwide.aclabs22.Aclabs22Application : No active profile set, falling back to default profiles: default
2025-06-07 15:26:54.091 DEBUG 23020 --- [           main] com.aciworldwide.aclabs22.utils.JWTAuthenticationFilter : Filter 'JWTAuthenticationFilter' configured for use
2025-06-07 15:26:54.919  INFO 23020 --- [           main] com.aciworldwide.aclabs22.Aclabs22Application : Started Aclabs22Application in 1.662 seconds (JVM running for 2.243)
2025-06-07 15:27:02.388 ERROR 23020 --- [nio-8080-exec-1] com.aciworldwide.aclabs22.services.AnomalyService : Python script exited with code 1
2025-06-07 15:27:02.388 ERROR 23020 --- [nio-8080-exec-1] com.aciworldwide.aclabs22.services.AnomalyService : Output/Error: Traceback (most recent call last):  File "/Users/dariofriskan/Documents/ACI-LigaACLabs2023-REST/src/model/predict.py", line 8, in <module>    model = joblib.load('model.pkl')            ^^^^^^^^^^^^^^^^^^^^^^^^  File "/opt/anaconda3/lib/python3.12/site-packages/joblib/numpy_pickle.py", line 650, in load    with open(filename, 'rb') as f:         ^^^^^^^^^^^^^^^^^^^^FileNotFoundError: [Errno 2] No such file or directory: 'model.pkl'
2025-06-07 15:27:10.594 ERROR 23020 --- [nio-8080-exec-3] com.aciworldwide.aclabs22.services.AnomalyService : Python script exited with code 1
2025-06-07 15:27:10.594 ERROR 23020 --- [nio-8080-exec-3] com.aciworldwide.aclabs22.services.AnomalyService : Output/Error: Traceback (most recent call last):  File "/Users/dariofriskan/Documents/ACI-LigaACLabs2023-REST/src/model/predict.py", line 8, in <module>    model = joblib.load('model.pkl')            ^^^^^^^^^^^^^^^^^^^^^^^^  File "/opt/anaconda3/lib/python3.12/site-packages/joblib/numpy_pickle.py", line 650, in load    with open(filename, 'rb') as f:         ^^^^^^^^^^^^^^^^^^^^FileNotFoundError: [Errno 2] No such file or directory: 'model.pkl'
2025-06-07 15:27:24.695  INFO 23020 --- [nio-8080-exec-5] com.aciworldwide.aclabs22.controllers.TransactionController : Received transaction request: TransactionDTO(cardNumber=1234567812345670, amount=123456.0, timestamp=2025-06-07 15:27:24.67)
2025-06-07 15:27:24.709  INFO 23020 --- [nio-8080-exec-5] com.aciworldwide.aclabs22.helpers.ValidationHelper : Validation succeeded with status: APPROVED and message: Transaction approved
2025-06-07 15:27:24.732  INFO 23020 --- [nio-8080-exec-5] com.aciworldwide.aclabs22.services.TransactionService : Transaction saved: 84
2025-06-07 15:27:27.338 ERROR 23020 --- [nio-8080-exec-6] com.aciworldwide.aclabs22.services.AnomalyService : Python script exited with code 1
2025-06-07 15:27:27.338 ERROR 23020 --- [nio-8080-exec-6] com.aciworldwide.aclabs22.services.AnomalyService : Output/Error: Traceback (most recent call last):  File "/Users/dariofriskan/Documents/ACI-LigaACLabs2023-REST/src/model/predict.py", line 8, in <module>    model = joblib.load('model.pkl')            ^^^^^^^^^^^^^^^^^^^^^^^^  File "/opt/anaconda3/lib/python3.12/site-packages/joblib/numpy_pickle.py", line 650, in load    with open(filename, 'rb') as f:         ^^^^^^^^^^^^^^^^^^^^FileNotFoundError: [Errno 2] No such file or directory: 'model.pkl'
2025-06-07 15:28:32.028 ERROR 23020 --- [nio-8080-exec-7] com.aciworldwide.aclabs22.services.AnomalyService : Python script exited with code 1
2025-06-07 15:28:32.029 ERROR 23020 --- [nio-8080-exec-7] com.aciworldwide.aclabs22.services.AnomalyService : Output/Error: Traceback (most recent call last):  File "/Users/dariofriskan/Documents/ACI-LigaACLabs2023-REST/src/model/predict.py", line 8, in <module>    model = joblib.load('model.pkl')            ^^^^^^^^^^^^^^^^^^^^^^^^  File "/opt/anaconda3/lib/python3.12/site-packages/joblib/numpy_pickle.py", line 650, in load    with open(filename, 'rb') as f:         ^^^^^^^^^^^^^^^^^^^^FileNotFoundError: [Errno 2] No such file or directory: 'model.pkl'
2025-06-07 15:31:36.396  INFO 23101 --- [           main] com.aciworldwide.aclabs22.Aclabs22Application : Starting Aclabs22Application using Java 24 on Darios-MacBook-Pro.local with PID 23101 (/Users/dariofriskan/Documents/ACI-LigaACLabs2023-REST/target/classes started by dariofriskan in /Users/dariofriskan/Documents/ACI-LigaACLabs2023-REST)
2025-06-07 15:31:36.399 DEBUG 23101 --- [           main] com.aciworldwide.aclabs22.Aclabs22Application : Running with Spring Boot v2.6.3, Spring v5.3.15
2025-06-07 15:31:36.399  INFO 23101 --- [           main] com.aciworldwide.aclabs22.Aclabs22Application : No active profile set, falling back to default profiles: default
2025-06-07 15:31:36.870 DEBUG 23101 --- [           main] com.aciworldwide.aclabs22.utils.JWTAuthenticationFilter : Filter 'JWTAuthenticationFilter' configured for use
2025-06-07 15:31:37.655  INFO 23101 --- [           main] com.aciworldwide.aclabs22.Aclabs22Application : Started Aclabs22Application in 1.369 seconds (JVM running for 1.74)
2025-06-07 15:31:49.957 ERROR 23101 --- [nio-8080-exec-1] com.aciworldwide.aclabs22.services.AnomalyService : Python script exited with code 1
2025-06-07 15:31:49.957 ERROR 23101 --- [nio-8080-exec-1] com.aciworldwide.aclabs22.services.AnomalyService : Output/Error: Traceback (most recent call last):  File "/Users/dariofriskan/Documents/ACI-LigaACLabs2023-REST/src/model/predict.py", line 8, in <module>    model = joblib.load('model.pkl')            ^^^^^^^^^^^^^^^^^^^^^^^^  File "/opt/anaconda3/lib/python3.12/site-packages/joblib/numpy_pickle.py", line 650, in load    with open(filename, 'rb') as f:         ^^^^^^^^^^^^^^^^^^^^FileNotFoundError: [Errno 2] No such file or directory: 'model.pkl'
2025-06-07 15:33:16.804 ERROR 23101 --- [nio-8080-exec-2] com.aciworldwide.aclabs22.services.AnomalyService : Python script exited with code 1
2025-06-07 15:33:16.804 ERROR 23101 --- [nio-8080-exec-2] com.aciworldwide.aclabs22.services.AnomalyService : Output/Error: Traceback (most recent call last):  File "/Users/dariofriskan/Documents/ACI-LigaACLabs2023-REST/src/model/predict.py", line 8, in <module>    model = joblib.load('model.pkl')            ^^^^^^^^^^^^^^^^^^^^^^^^  File "/opt/anaconda3/lib/python3.12/site-packages/joblib/numpy_pickle.py", line 650, in load    with open(filename, 'rb') as f:         ^^^^^^^^^^^^^^^^^^^^FileNotFoundError: [Errno 2] No such file or directory: 'model.pkl'
2025-06-07 15:35:06.823 ERROR 23101 --- [nio-8080-exec-3] com.aciworldwide.aclabs22.services.AnomalyService : Python script exited with code 1
2025-06-07 15:35:06.823 ERROR 23101 --- [nio-8080-exec-3] com.aciworldwide.aclabs22.services.AnomalyService : Output/Error: Traceback (most recent call last):  File "/Users/dariofriskan/Documents/ACI-LigaACLabs2023-REST/src/model/predict.py", line 8, in <module>    model = joblib.load('model.pkl')            ^^^^^^^^^^^^^^^^^^^^^^^^  File "/opt/anaconda3/lib/python3.12/site-packages/joblib/numpy_pickle.py", line 650, in load    with open(filename, 'rb') as f:         ^^^^^^^^^^^^^^^^^^^^FileNotFoundError: [Errno 2] No such file or directory: 'model.pkl'
2025-06-07 15:35:08.935 ERROR 23101 --- [nio-8080-exec-4] com.aciworldwide.aclabs22.services.AnomalyService : Python script exited with code 1
2025-06-07 15:35:08.935 ERROR 23101 --- [nio-8080-exec-4] com.aciworldwide.aclabs22.services.AnomalyService : Output/Error: Traceback (most recent call last):  File "/Users/dariofriskan/Documents/ACI-LigaACLabs2023-REST/src/model/predict.py", line 8, in <module>    model = joblib.load('model.pkl')            ^^^^^^^^^^^^^^^^^^^^^^^^  File "/opt/anaconda3/lib/python3.12/site-packages/joblib/numpy_pickle.py", line 650, in load    with open(filename, 'rb') as f:         ^^^^^^^^^^^^^^^^^^^^FileNotFoundError: [Errno 2] No such file or directory: 'model.pkl'
2025-06-07 15:35:44.284 ERROR 23101 --- [nio-8080-exec-5] com.aciworldwide.aclabs22.services.AnomalyService : Python script exited with code 1
2025-06-07 15:35:44.285 ERROR 23101 --- [nio-8080-exec-5] com.aciworldwide.aclabs22.services.AnomalyService : Output/Error: Traceback (most recent call last):  File "/Users/dariofriskan/Documents/ACI-LigaACLabs2023-REST/src/model/predict.py", line 8, in <module>    model = joblib.load('model.pkl')            ^^^^^^^^^^^^^^^^^^^^^^^^  File "/opt/anaconda3/lib/python3.12/site-packages/joblib/numpy_pickle.py", line 650, in load    with open(filename, 'rb') as f:         ^^^^^^^^^^^^^^^^^^^^FileNotFoundError: [Errno 2] No such file or directory: 'model.pkl'
2025-06-07 15:36:10.107 ERROR 23101 --- [nio-8080-exec-6] com.aciworldwide.aclabs22.services.AnomalyService : Python script exited with code 1
2025-06-07 15:36:10.108 ERROR 23101 --- [nio-8080-exec-6] com.aciworldwide.aclabs22.services.AnomalyService : Output/Error: Traceback (most recent call last):  File "/Users/dariofriskan/Documents/ACI-LigaACLabs2023-REST/src/model/predict.py", line 8, in <module>    model = joblib.load('model.pkl')            ^^^^^^^^^^^^^^^^^^^^^^^^  File "/opt/anaconda3/lib/python3.12/site-packages/joblib/numpy_pickle.py", line 650, in load    with open(filename, 'rb') as f:         ^^^^^^^^^^^^^^^^^^^^FileNotFoundError: [Errno 2] No such file or directory: 'model.pkl'
2025-06-07 15:55:17.375  INFO 23282 --- [           main] com.aciworldwide.aclabs22.Aclabs22Application : Starting Aclabs22Application using Java 24 on Darios-MacBook-Pro.local with PID 23282 (/Users/dariofriskan/Documents/ACI-LigaACLabs2023-REST/target/classes started by dariofriskan in /Users/dariofriskan/Documents/ACI-LigaACLabs2023-REST)
2025-06-07 15:55:17.378 DEBUG 23282 --- [           main] com.aciworldwide.aclabs22.Aclabs22Application : Running with Spring Boot v2.6.3, Spring v5.3.15
2025-06-07 15:55:17.378  INFO 23282 --- [           main] com.aciworldwide.aclabs22.Aclabs22Application : No active profile set, falling back to default profiles: default
2025-06-07 15:55:17.867 DEBUG 23282 --- [           main] com.aciworldwide.aclabs22.utils.JWTAuthenticationFilter : Filter 'JWTAuthenticationFilter' configured for use
2025-06-07 15:55:18.764  INFO 23282 --- [           main] com.aciworldwide.aclabs22.Aclabs22Application : Started Aclabs22Application in 1.51 seconds (JVM running for 2.009)
2025-06-07 16:37:01.730  INFO 23570 --- [           main] com.aciworldwide.aclabs22.Aclabs22Application : Starting Aclabs22Application using Java 24 on Darios-MacBook-Pro.local with PID 23570 (/Users/dariofriskan/Documents/ACI-LigaACLabs2023-REST/target/classes started by dariofriskan in /Users/dariofriskan/Documents/ACI-LigaACLabs2023-REST)
2025-06-07 16:37:01.733 DEBUG 23570 --- [           main] com.aciworldwide.aclabs22.Aclabs22Application : Running with Spring Boot v2.6.3, Spring v5.3.15
2025-06-07 16:37:01.733  INFO 23570 --- [           main] com.aciworldwide.aclabs22.Aclabs22Application : No active profile set, falling back to default profiles: default
2025-06-07 16:37:02.189 DEBUG 23570 --- [           main] com.aciworldwide.aclabs22.utils.JWTAuthenticationFilter : Filter 'JWTAuthenticationFilter' configured for use
2025-06-07 16:37:02.962  INFO 23570 --- [           main] com.aciworldwide.aclabs22.Aclabs22Application : Started Aclabs22Application in 1.355 seconds (JVM running for 1.765)
2025-06-07 16:37:13.458 ERROR 23570 --- [nio-8080-exec-1] com.aciworldwide.aclabs22.services.AnomalyService : Python script exited with code 1
2025-06-07 16:37:13.458 ERROR 23570 --- [nio-8080-exec-1] com.aciworldwide.aclabs22.services.AnomalyService : Output/Error: Traceback (most recent call last):  File "/Users/dariofriskan/Documents/ACI-LigaACLabs2023-REST/src/model/predict.py", line 31, in <module>    main()  File "/Users/dariofriskan/Documents/ACI-LigaACLabs2023-REST/src/model/predict.py", line 7, in main    model = joblib.load('model.pkl')            ^^^^^^^^^^^^^^^^^^^^^^^^  File "/opt/anaconda3/lib/python3.12/site-packages/joblib/numpy_pickle.py", line 650, in load    with open(filename, 'rb') as f:         ^^^^^^^^^^^^^^^^^^^^FileNotFoundError: [Errno 2] No such file or directory: 'model.pkl'
2025-06-07 16:37:18.562 ERROR 23570 --- [nio-8080-exec-2] com.aciworldwide.aclabs22.services.AnomalyService : Python script exited with code 1
2025-06-07 16:37:18.562 ERROR 23570 --- [nio-8080-exec-2] com.aciworldwide.aclabs22.services.AnomalyService : Output/Error: Traceback (most recent call last):  File "/Users/dariofriskan/Documents/ACI-LigaACLabs2023-REST/src/model/predict.py", line 31, in <module>    main()  File "/Users/dariofriskan/Documents/ACI-LigaACLabs2023-REST/src/model/predict.py", line 7, in main    model = joblib.load('model.pkl')            ^^^^^^^^^^^^^^^^^^^^^^^^  File "/opt/anaconda3/lib/python3.12/site-packages/joblib/numpy_pickle.py", line 650, in load    with open(filename, 'rb') as f:         ^^^^^^^^^^^^^^^^^^^^FileNotFoundError: [Errno 2] No such file or directory: 'model.pkl'
2025-06-07 16:37:23.031 ERROR 23570 --- [nio-8080-exec-3] com.aciworldwide.aclabs22.services.AnomalyService : Python script exited with code 1
2025-06-07 16:37:23.031 ERROR 23570 --- [nio-8080-exec-3] com.aciworldwide.aclabs22.services.AnomalyService : Output/Error: Traceback (most recent call last):  File "/Users/dariofriskan/Documents/ACI-LigaACLabs2023-REST/src/model/predict.py", line 31, in <module>    main()  File "/Users/dariofriskan/Documents/ACI-LigaACLabs2023-REST/src/model/predict.py", line 7, in main    model = joblib.load('model.pkl')            ^^^^^^^^^^^^^^^^^^^^^^^^  File "/opt/anaconda3/lib/python3.12/site-packages/joblib/numpy_pickle.py", line 650, in load    with open(filename, 'rb') as f:         ^^^^^^^^^^^^^^^^^^^^FileNotFoundError: [Errno 2] No such file or directory: 'model.pkl'
2025-06-07 16:37:31.724 ERROR 23570 --- [nio-8080-exec-7] com.aciworldwide.aclabs22.services.AnomalyService : Python script exited with code 1
2025-06-07 16:37:31.724 ERROR 23570 --- [nio-8080-exec-7] com.aciworldwide.aclabs22.services.AnomalyService : Output/Error: Traceback (most recent call last):  File "/Users/dariofriskan/Documents/ACI-LigaACLabs2023-REST/src/model/predict.py", line 31, in <module>    main()  File "/Users/dariofriskan/Documents/ACI-LigaACLabs2023-REST/src/model/predict.py", line 7, in main    model = joblib.load('model.pkl')            ^^^^^^^^^^^^^^^^^^^^^^^^  File "/opt/anaconda3/lib/python3.12/site-packages/joblib/numpy_pickle.py", line 650, in load    with open(filename, 'rb') as f:         ^^^^^^^^^^^^^^^^^^^^FileNotFoundError: [Errno 2] No such file or directory: 'model.pkl'
2025-06-07 16:37:51.401  INFO 23570 --- [io-8080-exec-10] com.aciworldwide.aclabs22.controllers.TransactionController : Received transaction request: TransactionDTO(cardNumber=1234567812345670, amount=20000.0, timestamp=2025-06-07 16:37:51.376)
2025-06-07 16:37:51.416  INFO 23570 --- [io-8080-exec-10] com.aciworldwide.aclabs22.helpers.ValidationHelper : Validation succeeded with status: APPROVED and message: Transaction approved
2025-06-07 16:37:51.447  INFO 23570 --- [io-8080-exec-10] com.aciworldwide.aclabs22.services.TransactionService : Transaction saved: 85
2025-06-07 16:37:54.051 ERROR 23570 --- [nio-8080-exec-1] com.aciworldwide.aclabs22.services.AnomalyService : Python script exited with code 1
2025-06-07 16:37:54.051 ERROR 23570 --- [nio-8080-exec-1] com.aciworldwide.aclabs22.services.AnomalyService : Output/Error: Traceback (most recent call last):  File "/Users/dariofriskan/Documents/ACI-LigaACLabs2023-REST/src/model/predict.py", line 31, in <module>    main()  File "/Users/dariofriskan/Documents/ACI-LigaACLabs2023-REST/src/model/predict.py", line 7, in main    model = joblib.load('model.pkl')            ^^^^^^^^^^^^^^^^^^^^^^^^  File "/opt/anaconda3/lib/python3.12/site-packages/joblib/numpy_pickle.py", line 650, in load    with open(filename, 'rb') as f:         ^^^^^^^^^^^^^^^^^^^^FileNotFoundError: [Errno 2] No such file or directory: 'model.pkl'
2025-06-07 16:46:27.851  INFO 23686 --- [           main] com.aciworldwide.aclabs22.Aclabs22Application : Starting Aclabs22Application using Java 24 on Darios-MacBook-Pro.local with PID 23686 (/Users/dariofriskan/Documents/ACI-LigaACLabs2023-REST/target/classes started by dariofriskan in /Users/dariofriskan/Documents/ACI-LigaACLabs2023-REST)
2025-06-07 16:46:27.854 DEBUG 23686 --- [           main] com.aciworldwide.aclabs22.Aclabs22Application : Running with Spring Boot v2.6.3, Spring v5.3.15
2025-06-07 16:46:27.854  INFO 23686 --- [           main] com.aciworldwide.aclabs22.Aclabs22Application : No active profile set, falling back to default profiles: default
2025-06-07 16:46:28.348 DEBUG 23686 --- [           main] com.aciworldwide.aclabs22.utils.JWTAuthenticationFilter : Filter 'JWTAuthenticationFilter' configured for use
2025-06-07 16:46:29.153  INFO 23686 --- [           main] com.aciworldwide.aclabs22.Aclabs22Application : Started Aclabs22Application in 1.423 seconds (JVM running for 1.895)
2025-06-07 16:46:35.544  INFO 23686 --- [nio-8080-exec-1] com.aciworldwide.aclabs22.services.AnomalyService : JSON input to Python script: [{"cardNumber":"1234567812345670","amount":10.0,"timestamp":1745593082191},{"cardNumber":"1234567812345670","amount":100.0,"timestamp":1745593172794},{"cardNumber":"1234567812345670","amount":100.0,"timestamp":1745593262274},{"cardNumber":"1234567812345670","amount":1009102.0,"timestamp":1745595529759},{"cardNumber":"1234567812345670","amount":1009102.0,"timestamp":1745595567214},{"cardNumber":"1234567812345670","amount":1009102.0,"timestamp":1745595812805},{"cardNumber":"1234567812345670","amount":11.0,"timestamp":1745595869876},{"cardNumber":"1234567812345670","amount":110000.0,"timestamp":1745595939486},{"cardNumber":"1234567812345670","amount":110000.0,"timestamp":1745596107459},{"cardNumber":"1234567812345670","amount":110.0,"timestamp":1745596608417},{"cardNumber":"1234567812345670","amount":22220.0,"timestamp":1745596629599},{"cardNumber":"1234567812345670","amount":22220.0,"timestamp":1745596649335},{"cardNumber":"1234567812345670","amount":2.2E7,"timestamp":1745596862340},{"cardNumber":"1234567812345670","amount":22.0,"timestamp":1745596882101},{"cardNumber":"1234567812345670","amount":22.0,"timestamp":1745940855222},{"cardNumber":"1234567812345670","amount":42500.0,"timestamp":1749300717570},{"cardNumber":"1234567812345670","amount":7000.0,"timestamp":1749005100000},{"cardNumber":"1234567812345670","amount":123456.0,"timestamp":1749302844670},{"cardNumber":"1234567812345670","amount":20000.0,"timestamp":1749307071376}]
2025-06-07 16:46:36.138  INFO 23686 --- [nio-8080-exec-1] com.aciworldwide.aclabs22.services.AnomalyService : Python script exit code: 1
2025-06-07 16:46:36.138  INFO 23686 --- [nio-8080-exec-1] com.aciworldwide.aclabs22.services.AnomalyService : Python script output: Traceback (most recent call last):  File "/Users/dariofriskan/Documents/ACI-LigaACLabs2023-REST/src/model/predict.py", line 37, in <module>    main()  File "/Users/dariofriskan/Documents/ACI-LigaACLabs2023-REST/src/model/predict.py", line 7, in main    model = joblib.load('model.pkl')            ^^^^^^^^^^^^^^^^^^^^^^^^  File "/opt/anaconda3/lib/python3.12/site-packages/joblib/numpy_pickle.py", line 650, in load    with open(filename, 'rb') as f:         ^^^^^^^^^^^^^^^^^^^^FileNotFoundError: [Errno 2] No such file or directory: 'model.pkl'
2025-06-07 16:46:36.138 ERROR 23686 --- [nio-8080-exec-1] com.aciworldwide.aclabs22.services.AnomalyService : Python script exited with code 1
2025-06-07 16:46:59.102  INFO 23686 --- [nio-8080-exec-3] com.aciworldwide.aclabs22.controllers.TransactionController : Received transaction request: TransactionDTO(cardNumber=1234567812345670, amount=19999.0, timestamp=2025-06-07 16:46:59.077)
2025-06-07 16:46:59.115  INFO 23686 --- [nio-8080-exec-3] com.aciworldwide.aclabs22.helpers.ValidationHelper : Validation succeeded with status: APPROVED and message: Transaction approved
2025-06-07 16:46:59.130  INFO 23686 --- [nio-8080-exec-3] com.aciworldwide.aclabs22.services.TransactionService : Transaction saved: 86
2025-06-07 16:47:19.262  INFO 23686 --- [nio-8080-exec-4] com.aciworldwide.aclabs22.services.AnomalyService : JSON input to Python script: [{"cardNumber":"1234567812345670","amount":10.0,"timestamp":1745593082191},{"cardNumber":"1234567812345670","amount":100.0,"timestamp":1745593172794},{"cardNumber":"1234567812345670","amount":100.0,"timestamp":1745593262274},{"cardNumber":"1234567812345670","amount":1009102.0,"timestamp":1745595529759},{"cardNumber":"1234567812345670","amount":1009102.0,"timestamp":1745595567214},{"cardNumber":"1234567812345670","amount":1009102.0,"timestamp":1745595812805},{"cardNumber":"1234567812345670","amount":11.0,"timestamp":1745595869876},{"cardNumber":"1234567812345670","amount":110000.0,"timestamp":1745595939486},{"cardNumber":"1234567812345670","amount":110000.0,"timestamp":1745596107459},{"cardNumber":"1234567812345670","amount":110.0,"timestamp":1745596608417},{"cardNumber":"1234567812345670","amount":22220.0,"timestamp":1745596629599},{"cardNumber":"1234567812345670","amount":22220.0,"timestamp":1745596649335},{"cardNumber":"1234567812345670","amount":2.2E7,"timestamp":1745596862340},{"cardNumber":"1234567812345670","amount":22.0,"timestamp":1745596882101},{"cardNumber":"1234567812345670","amount":22.0,"timestamp":1745940855222},{"cardNumber":"1234567812345670","amount":42500.0,"timestamp":1749300717570},{"cardNumber":"1234567812345670","amount":7000.0,"timestamp":1749005100000},{"cardNumber":"1234567812345670","amount":123456.0,"timestamp":1749302844670},{"cardNumber":"1234567812345670","amount":20000.0,"timestamp":1749307071376},{"cardNumber":"1234567812345670","amount":19999.0,"timestamp":1749307619077}]
2025-06-07 16:47:19.863  INFO 23686 --- [nio-8080-exec-4] com.aciworldwide.aclabs22.services.AnomalyService : Python script exit code: 1
2025-06-07 16:47:19.863  INFO 23686 --- [nio-8080-exec-4] com.aciworldwide.aclabs22.services.AnomalyService : Python script output: Traceback (most recent call last):  File "/Users/dariofriskan/Documents/ACI-LigaACLabs2023-REST/src/model/predict.py", line 37, in <module>    main()  File "/Users/dariofriskan/Documents/ACI-LigaACLabs2023-REST/src/model/predict.py", line 7, in main    model = joblib.load('model.pkl')            ^^^^^^^^^^^^^^^^^^^^^^^^  File "/opt/anaconda3/lib/python3.12/site-packages/joblib/numpy_pickle.py", line 650, in load    with open(filename, 'rb') as f:         ^^^^^^^^^^^^^^^^^^^^FileNotFoundError: [Errno 2] No such file or directory: 'model.pkl'
2025-06-07 16:47:19.863 ERROR 23686 --- [nio-8080-exec-4] com.aciworldwide.aclabs22.services.AnomalyService : Python script exited with code 1
2025-06-07 16:50:56.758  INFO 23730 --- [           main] com.aciworldwide.aclabs22.Aclabs22Application : Starting Aclabs22Application using Java 24 on Darios-MacBook-Pro.local with PID 23730 (/Users/dariofriskan/Documents/ACI-LigaACLabs2023-REST/target/classes started by dariofriskan in /Users/dariofriskan/Documents/ACI-LigaACLabs2023-REST)
2025-06-07 16:50:56.760 DEBUG 23730 --- [           main] com.aciworldwide.aclabs22.Aclabs22Application : Running with Spring Boot v2.6.3, Spring v5.3.15
2025-06-07 16:50:56.760  INFO 23730 --- [           main] com.aciworldwide.aclabs22.Aclabs22Application : No active profile set, falling back to default profiles: default
2025-06-07 16:50:57.243 DEBUG 23730 --- [           main] com.aciworldwide.aclabs22.utils.JWTAuthenticationFilter : Filter 'JWTAuthenticationFilter' configured for use
2025-06-07 16:50:58.028  INFO 23730 --- [           main] com.aciworldwide.aclabs22.Aclabs22Application : Started Aclabs22Application in 1.383 seconds (JVM running for 1.751)
2025-06-07 16:51:03.297  INFO 23730 --- [nio-8080-exec-1] com.aciworldwide.aclabs22.services.AnomalyService : Starting anomaly detection for 20 transactions
2025-06-07 16:51:03.297 DEBUG 23730 --- [nio-8080-exec-1] com.aciworldwide.aclabs22.services.AnomalyService : ProcessBuilder command: [python3, /Users/dariofriskan/Documents/ACI-LigaACLabs2023-REST/src/model/predict.py]
2025-06-07 16:51:03.302  INFO 23730 --- [nio-8080-exec-1] com.aciworldwide.aclabs22.services.AnomalyService : Python process started
2025-06-07 16:51:03.312  INFO 23730 --- [nio-8080-exec-1] com.aciworldwide.aclabs22.services.AnomalyService : Serialized JSON input size: 1529 bytes
2025-06-07 16:51:03.312 DEBUG 23730 --- [nio-8080-exec-1] com.aciworldwide.aclabs22.services.AnomalyService : JSON input to Python script: [{"cardNumber":"1234567812345670","amount":10.0,"timestamp":1745593082191},{"cardNumber":"1234567812345670","amount":100.0,"timestamp":1745593172794},{"cardNumber":"1234567812345670","amount":100.0,"timestamp":1745593262274},{"cardNumber":"1234567812345670","amount":1009102.0,"timestamp":1745595529759},{"cardNumber":"1234567812345670","amount":1009102.0,"timestamp":1745595567214},{"cardNumber":"1234567812345670","amount":1009102.0,"timestamp":1745595812805},{"cardNumber":"1234567812345670","amount":11.0,"timestamp":1745595869876},{"cardNumber":"1234567812345670","amount":110000.0,"timestamp":1745595939486},{"cardNumber":"1234567812345670","amount":110000.0,"timestamp":1745596107459},{"cardNumber":"1234567812345670","amount":110.0,"timestamp":1745596608417},{"cardNumber":"1234567812345670","amount":22220.0,"timestamp":1745596629599},{"cardNumber":"1234567812345670","amount":22220.0,"timestamp":1745596649335},{"cardNumber":"1234567812345670","amount":2.2E7,"timestamp":1745596862340},{"cardNumber":"1234567812345670","amount":22.0,"timestamp":1745596882101},{"cardNumber":"1234567812345670","amount":22.0,"timestamp":1745940855222},{"cardNumber":"1234567812345670","amount":42500.0,"timestamp":1749300717570},{"cardNumber":"1234567812345670","amount":7000.0,"timestamp":1749005100000},{"cardNumber":"1234567812345670","amount":123456.0,"timestamp":1749302844670},{"cardNumber":"1234567812345670","amount":20000.0,"timestamp":1749307071376},{"cardNumber":"1234567812345670","amount":19999.0,"timestamp":1749307619077}]
2025-06-07 16:51:03.312  INFO 23730 --- [nio-8080-exec-1] com.aciworldwide.aclabs22.services.AnomalyService : JSON input sent to Python script
2025-06-07 16:51:03.888 DEBUG 23730 --- [nio-8080-exec-1] com.aciworldwide.aclabs22.services.AnomalyService : Python output line: Traceback (most recent call last):
2025-06-07 16:51:03.888 DEBUG 23730 --- [nio-8080-exec-1] com.aciworldwide.aclabs22.services.AnomalyService : Python output line:   File "/Users/dariofriskan/Documents/ACI-LigaACLabs2023-REST/src/model/predict.py", line 37, in <module>
2025-06-07 16:51:03.888 DEBUG 23730 --- [nio-8080-exec-1] com.aciworldwide.aclabs22.services.AnomalyService : Python output line:     main()
2025-06-07 16:51:03.888 DEBUG 23730 --- [nio-8080-exec-1] com.aciworldwide.aclabs22.services.AnomalyService : Python output line:   File "/Users/dariofriskan/Documents/ACI-LigaACLabs2023-REST/src/model/predict.py", line 7, in main
2025-06-07 16:51:03.888 DEBUG 23730 --- [nio-8080-exec-1] com.aciworldwide.aclabs22.services.AnomalyService : Python output line:     model = joblib.load('model.pkl')
2025-06-07 16:51:03.888 DEBUG 23730 --- [nio-8080-exec-1] com.aciworldwide.aclabs22.services.AnomalyService : Python output line:             ^^^^^^^^^^^^^^^^^^^^^^^^
2025-06-07 16:51:03.888 DEBUG 23730 --- [nio-8080-exec-1] com.aciworldwide.aclabs22.services.AnomalyService : Python output line:   File "/opt/anaconda3/lib/python3.12/site-packages/joblib/numpy_pickle.py", line 650, in load
2025-06-07 16:51:03.888 DEBUG 23730 --- [nio-8080-exec-1] com.aciworldwide.aclabs22.services.AnomalyService : Python output line:     with open(filename, 'rb') as f:
2025-06-07 16:51:03.888 DEBUG 23730 --- [nio-8080-exec-1] com.aciworldwide.aclabs22.services.AnomalyService : Python output line:          ^^^^^^^^^^^^^^^^^^^^
2025-06-07 16:51:03.888 DEBUG 23730 --- [nio-8080-exec-1] com.aciworldwide.aclabs22.services.AnomalyService : Python output line: FileNotFoundError: [Errno 2] No such file or directory: 'model.pkl'
2025-06-07 16:51:03.917  INFO 23730 --- [nio-8080-exec-1] com.aciworldwide.aclabs22.services.AnomalyService : Finished reading output from Python script
2025-06-07 16:51:03.917  INFO 23730 --- [nio-8080-exec-1] com.aciworldwide.aclabs22.services.AnomalyService : Python script exited with code: 1
2025-06-07 16:51:03.917 ERROR 23730 --- [nio-8080-exec-1] com.aciworldwide.aclabs22.services.AnomalyService : Python script exited with non-zero code: 1
2025-06-07 16:51:34.638  INFO 23730 --- [nio-8080-exec-5] com.aciworldwide.aclabs22.controllers.TransactionController : Received transaction request: TransactionDTO(cardNumber=1234567812345670, amount=19998.0, timestamp=2025-06-07 16:51:34.614)
2025-06-07 16:51:34.652  INFO 23730 --- [nio-8080-exec-5] com.aciworldwide.aclabs22.helpers.ValidationHelper : Validation succeeded with status: APPROVED and message: Transaction approved
2025-06-07 16:51:34.667  INFO 23730 --- [nio-8080-exec-5] com.aciworldwide.aclabs22.services.TransactionService : Transaction saved: 87
2025-06-07 16:51:52.321  INFO 23730 --- [nio-8080-exec-6] com.aciworldwide.aclabs22.services.AnomalyService : Starting anomaly detection for 21 transactions
2025-06-07 16:51:52.321 DEBUG 23730 --- [nio-8080-exec-6] com.aciworldwide.aclabs22.services.AnomalyService : ProcessBuilder command: [python3, /Users/dariofriskan/Documents/ACI-LigaACLabs2023-REST/src/model/predict.py]
2025-06-07 16:51:52.329  INFO 23730 --- [nio-8080-exec-6] com.aciworldwide.aclabs22.services.AnomalyService : Python process started
2025-06-07 16:51:52.329  INFO 23730 --- [nio-8080-exec-6] com.aciworldwide.aclabs22.services.AnomalyService : Serialized JSON input size: 1606 bytes
2025-06-07 16:51:52.329 DEBUG 23730 --- [nio-8080-exec-6] com.aciworldwide.aclabs22.services.AnomalyService : JSON input to Python script: [{"cardNumber":"1234567812345670","amount":10.0,"timestamp":1745593082191},{"cardNumber":"1234567812345670","amount":100.0,"timestamp":1745593172794},{"cardNumber":"1234567812345670","amount":100.0,"timestamp":1745593262274},{"cardNumber":"1234567812345670","amount":1009102.0,"timestamp":1745595529759},{"cardNumber":"1234567812345670","amount":1009102.0,"timestamp":1745595567214},{"cardNumber":"1234567812345670","amount":1009102.0,"timestamp":1745595812805},{"cardNumber":"1234567812345670","amount":11.0,"timestamp":1745595869876},{"cardNumber":"1234567812345670","amount":110000.0,"timestamp":1745595939486},{"cardNumber":"1234567812345670","amount":110000.0,"timestamp":1745596107459},{"cardNumber":"1234567812345670","amount":110.0,"timestamp":1745596608417},{"cardNumber":"1234567812345670","amount":22220.0,"timestamp":1745596629599},{"cardNumber":"1234567812345670","amount":22220.0,"timestamp":1745596649335},{"cardNumber":"1234567812345670","amount":2.2E7,"timestamp":1745596862340},{"cardNumber":"1234567812345670","amount":22.0,"timestamp":1745596882101},{"cardNumber":"1234567812345670","amount":22.0,"timestamp":1745940855222},{"cardNumber":"1234567812345670","amount":42500.0,"timestamp":1749300717570},{"cardNumber":"1234567812345670","amount":7000.0,"timestamp":1749005100000},{"cardNumber":"1234567812345670","amount":123456.0,"timestamp":1749302844670},{"cardNumber":"1234567812345670","amount":20000.0,"timestamp":1749307071376},{"cardNumber":"1234567812345670","amount":19999.0,"timestamp":1749307619077},{"cardNumber":"1234567812345670","amount":19998.0,"timestamp":1749307894614}]
2025-06-07 16:51:52.330  INFO 23730 --- [nio-8080-exec-6] com.aciworldwide.aclabs22.services.AnomalyService : JSON input sent to Python script
2025-06-07 16:51:52.907 DEBUG 23730 --- [nio-8080-exec-6] com.aciworldwide.aclabs22.services.AnomalyService : Python output line: Traceback (most recent call last):
2025-06-07 16:51:52.907 DEBUG 23730 --- [nio-8080-exec-6] com.aciworldwide.aclabs22.services.AnomalyService : Python output line:   File "/Users/dariofriskan/Documents/ACI-LigaACLabs2023-REST/src/model/predict.py", line 37, in <module>
2025-06-07 16:51:52.907 DEBUG 23730 --- [nio-8080-exec-6] com.aciworldwide.aclabs22.services.AnomalyService : Python output line:     main()
2025-06-07 16:51:52.907 DEBUG 23730 --- [nio-8080-exec-6] com.aciworldwide.aclabs22.services.AnomalyService : Python output line:   File "/Users/dariofriskan/Documents/ACI-LigaACLabs2023-REST/src/model/predict.py", line 7, in main
2025-06-07 16:51:52.907 DEBUG 23730 --- [nio-8080-exec-6] com.aciworldwide.aclabs22.services.AnomalyService : Python output line:     model = joblib.load('model.pkl')
2025-06-07 16:51:52.907 DEBUG 23730 --- [nio-8080-exec-6] com.aciworldwide.aclabs22.services.AnomalyService : Python output line:             ^^^^^^^^^^^^^^^^^^^^^^^^
2025-06-07 16:51:52.907 DEBUG 23730 --- [nio-8080-exec-6] com.aciworldwide.aclabs22.services.AnomalyService : Python output line:   File "/opt/anaconda3/lib/python3.12/site-packages/joblib/numpy_pickle.py", line 650, in load
2025-06-07 16:51:52.907 DEBUG 23730 --- [nio-8080-exec-6] com.aciworldwide.aclabs22.services.AnomalyService : Python output line:     with open(filename, 'rb') as f:
2025-06-07 16:51:52.907 DEBUG 23730 --- [nio-8080-exec-6] com.aciworldwide.aclabs22.services.AnomalyService : Python output line:          ^^^^^^^^^^^^^^^^^^^^
2025-06-07 16:51:52.907 DEBUG 23730 --- [nio-8080-exec-6] com.aciworldwide.aclabs22.services.AnomalyService : Python output line: FileNotFoundError: [Errno 2] No such file or directory: 'model.pkl'
2025-06-07 16:51:52.940  INFO 23730 --- [nio-8080-exec-6] com.aciworldwide.aclabs22.services.AnomalyService : Finished reading output from Python script
2025-06-07 16:51:52.940  INFO 23730 --- [nio-8080-exec-6] com.aciworldwide.aclabs22.services.AnomalyService : Python script exited with code: 1
2025-06-07 16:51:52.940 ERROR 23730 --- [nio-8080-exec-6] com.aciworldwide.aclabs22.services.AnomalyService : Python script exited with non-zero code: 1
2025-06-07 17:05:28.427  INFO 23923 --- [           main] com.aciworldwide.aclabs22.Aclabs22Application : Starting Aclabs22Application using Java 24 on Darios-MacBook-Pro.local with PID 23923 (/Users/dariofriskan/Documents/ACI-LigaACLabs2023-REST/target/classes started by dariofriskan in /Users/dariofriskan/Documents/ACI-LigaACLabs2023-REST)
2025-06-07 17:05:28.429 DEBUG 23923 --- [           main] com.aciworldwide.aclabs22.Aclabs22Application : Running with Spring Boot v2.6.3, Spring v5.3.15
2025-06-07 17:05:28.429  INFO 23923 --- [           main] com.aciworldwide.aclabs22.Aclabs22Application : No active profile set, falling back to default profiles: default
2025-06-07 17:05:28.873 DEBUG 23923 --- [           main] com.aciworldwide.aclabs22.utils.JWTAuthenticationFilter : Filter 'JWTAuthenticationFilter' configured for use
2025-06-07 17:05:29.643  INFO 23923 --- [           main] com.aciworldwide.aclabs22.Aclabs22Application : Started Aclabs22Application in 1.327 seconds (JVM running for 1.705)
2025-06-07 17:08:11.698  INFO 24028 --- [           main] com.aciworldwide.aclabs22.Aclabs22Application : Starting Aclabs22Application using Java 24 on Darios-MacBook-Pro.local with PID 24028 (/Users/dariofriskan/Documents/ACI-LigaACLabs2023-REST/target/classes started by dariofriskan in /Users/dariofriskan/Documents/ACI-LigaACLabs2023-REST)
2025-06-07 17:08:11.701 DEBUG 24028 --- [           main] com.aciworldwide.aclabs22.Aclabs22Application : Running with Spring Boot v2.6.3, Spring v5.3.15
2025-06-07 17:08:11.701  INFO 24028 --- [           main] com.aciworldwide.aclabs22.Aclabs22Application : No active profile set, falling back to default profiles: default
2025-06-07 17:08:12.165 DEBUG 24028 --- [           main] com.aciworldwide.aclabs22.utils.JWTAuthenticationFilter : Filter 'JWTAuthenticationFilter' configured for use
2025-06-07 17:08:12.944  INFO 24028 --- [           main] com.aciworldwide.aclabs22.Aclabs22Application : Started Aclabs22Application in 1.407 seconds (JVM running for 1.908)
2025-06-07 17:08:25.028  INFO 24028 --- [nio-8080-exec-1] com.aciworldwide.aclabs22.services.AnomalyService : Starting anomaly detection for 21 transactions
2025-06-07 17:08:25.028 DEBUG 24028 --- [nio-8080-exec-1] com.aciworldwide.aclabs22.services.AnomalyService : ProcessBuilder command: [python3, /Users/dariofriskan/Documents/ACI-LigaACLabs2023-REST/src/model/predict.py]
2025-06-07 17:08:25.033  INFO 24028 --- [nio-8080-exec-1] com.aciworldwide.aclabs22.services.AnomalyService : Python process started
2025-06-07 17:08:25.049  INFO 24028 --- [nio-8080-exec-1] com.aciworldwide.aclabs22.services.AnomalyService : Serialized JSON input size: 1606 bytes
2025-06-07 17:08:25.050 DEBUG 24028 --- [nio-8080-exec-1] com.aciworldwide.aclabs22.services.AnomalyService : JSON input to Python script: [{"cardNumber":"1234567812345670","amount":10.0,"timestamp":1745593082191},{"cardNumber":"1234567812345670","amount":100.0,"timestamp":1745593172794},{"cardNumber":"1234567812345670","amount":100.0,"timestamp":1745593262274},{"cardNumber":"1234567812345670","amount":1009102.0,"timestamp":1745595529759},{"cardNumber":"1234567812345670","amount":1009102.0,"timestamp":1745595567214},{"cardNumber":"1234567812345670","amount":1009102.0,"timestamp":1745595812805},{"cardNumber":"1234567812345670","amount":11.0,"timestamp":1745595869876},{"cardNumber":"1234567812345670","amount":110000.0,"timestamp":1745595939486},{"cardNumber":"1234567812345670","amount":110000.0,"timestamp":1745596107459},{"cardNumber":"1234567812345670","amount":110.0,"timestamp":1745596608417},{"cardNumber":"1234567812345670","amount":22220.0,"timestamp":1745596629599},{"cardNumber":"1234567812345670","amount":22220.0,"timestamp":1745596649335},{"cardNumber":"1234567812345670","amount":2.2E7,"timestamp":1745596862340},{"cardNumber":"1234567812345670","amount":22.0,"timestamp":1745596882101},{"cardNumber":"1234567812345670","amount":22.0,"timestamp":1745940855222},{"cardNumber":"1234567812345670","amount":42500.0,"timestamp":1749300717570},{"cardNumber":"1234567812345670","amount":7000.0,"timestamp":1749005100000},{"cardNumber":"1234567812345670","amount":123456.0,"timestamp":1749302844670},{"cardNumber":"1234567812345670","amount":20000.0,"timestamp":1749307071376},{"cardNumber":"1234567812345670","amount":19999.0,"timestamp":1749307619077},{"cardNumber":"1234567812345670","amount":19998.0,"timestamp":1749307894614}]
2025-06-07 17:08:25.050  INFO 24028 --- [nio-8080-exec-1] com.aciworldwide.aclabs22.services.AnomalyService : JSON input sent to Python script
2025-06-07 17:08:25.647 DEBUG 24028 --- [nio-8080-exec-1] com.aciworldwide.aclabs22.services.AnomalyService : Python output line: Traceback (most recent call last):
2025-06-07 17:08:25.647 DEBUG 24028 --- [nio-8080-exec-1] com.aciworldwide.aclabs22.services.AnomalyService : Python output line:   File "/Users/dariofriskan/Documents/ACI-LigaACLabs2023-REST/src/model/predict.py", line 37, in <module>
2025-06-07 17:08:25.647 DEBUG 24028 --- [nio-8080-exec-1] com.aciworldwide.aclabs22.services.AnomalyService : Python output line:     main()
2025-06-07 17:08:25.648 DEBUG 24028 --- [nio-8080-exec-1] com.aciworldwide.aclabs22.services.AnomalyService : Python output line:   File "/Users/dariofriskan/Documents/ACI-LigaACLabs2023-REST/src/model/predict.py", line 7, in main
2025-06-07 17:08:25.648 DEBUG 24028 --- [nio-8080-exec-1] com.aciworldwide.aclabs22.services.AnomalyService : Python output line:     model = joblib.load('model.pkl')
2025-06-07 17:08:25.648 DEBUG 24028 --- [nio-8080-exec-1] com.aciworldwide.aclabs22.services.AnomalyService : Python output line:             ^^^^^^^^^^^^^^^^^^^^^^^^
2025-06-07 17:08:25.648 DEBUG 24028 --- [nio-8080-exec-1] com.aciworldwide.aclabs22.services.AnomalyService : Python output line:   File "/opt/anaconda3/lib/python3.12/site-packages/joblib/numpy_pickle.py", line 650, in load
2025-06-07 17:08:25.648 DEBUG 24028 --- [nio-8080-exec-1] com.aciworldwide.aclabs22.services.AnomalyService : Python output line:     with open(filename, 'rb') as f:
2025-06-07 17:08:25.648 DEBUG 24028 --- [nio-8080-exec-1] com.aciworldwide.aclabs22.services.AnomalyService : Python output line:          ^^^^^^^^^^^^^^^^^^^^
2025-06-07 17:08:25.648 DEBUG 24028 --- [nio-8080-exec-1] com.aciworldwide.aclabs22.services.AnomalyService : Python output line: FileNotFoundError: [Errno 2] No such file or directory: 'model.pkl'
2025-06-07 17:08:25.677  INFO 24028 --- [nio-8080-exec-1] com.aciworldwide.aclabs22.services.AnomalyService : Finished reading output from Python script
2025-06-07 17:08:25.677  INFO 24028 --- [nio-8080-exec-1] com.aciworldwide.aclabs22.services.AnomalyService : Python script exited with code: 1
2025-06-07 17:08:25.677 ERROR 24028 --- [nio-8080-exec-1] com.aciworldwide.aclabs22.services.AnomalyService : Python script exited with non-zero code: 1
2025-06-07 17:09:17.707  INFO 24087 --- [           main] com.aciworldwide.aclabs22.Aclabs22Application : Starting Aclabs22Application using Java 24 on Darios-MacBook-Pro.local with PID 24087 (/Users/dariofriskan/Documents/ACI-LigaACLabs2023-REST/target/classes started by dariofriskan in /Users/dariofriskan/Documents/ACI-LigaACLabs2023-REST)
2025-06-07 17:09:17.709 DEBUG 24087 --- [           main] com.aciworldwide.aclabs22.Aclabs22Application : Running with Spring Boot v2.6.3, Spring v5.3.15
2025-06-07 17:09:17.709  INFO 24087 --- [           main] com.aciworldwide.aclabs22.Aclabs22Application : No active profile set, falling back to default profiles: default
2025-06-07 17:09:18.182 DEBUG 24087 --- [           main] com.aciworldwide.aclabs22.utils.JWTAuthenticationFilter : Filter 'JWTAuthenticationFilter' configured for use
2025-06-07 17:09:18.947  INFO 24087 --- [           main] com.aciworldwide.aclabs22.Aclabs22Application : Started Aclabs22Application in 1.369 seconds (JVM running for 1.755)
2025-06-07 17:09:32.008  INFO 24087 --- [nio-8080-exec-1] com.aciworldwide.aclabs22.services.AnomalyService : Starting anomaly detection for 21 transactions
2025-06-07 17:09:32.008 DEBUG 24087 --- [nio-8080-exec-1] com.aciworldwide.aclabs22.services.AnomalyService : ProcessBuilder command: [python3, /Users/dariofriskan/Documents/ACI-LigaACLabs2023-REST/src/model/predict.py]
2025-06-07 17:09:32.013  INFO 24087 --- [nio-8080-exec-1] com.aciworldwide.aclabs22.services.AnomalyService : Python process started
2025-06-07 17:09:32.022  INFO 24087 --- [nio-8080-exec-1] com.aciworldwide.aclabs22.services.AnomalyService : Serialized JSON input size: 1606 bytes
2025-06-07 17:09:32.022 DEBUG 24087 --- [nio-8080-exec-1] com.aciworldwide.aclabs22.services.AnomalyService : JSON input to Python script: [{"cardNumber":"1234567812345670","amount":10.0,"timestamp":1745593082191},{"cardNumber":"1234567812345670","amount":100.0,"timestamp":1745593172794},{"cardNumber":"1234567812345670","amount":100.0,"timestamp":1745593262274},{"cardNumber":"1234567812345670","amount":1009102.0,"timestamp":1745595529759},{"cardNumber":"1234567812345670","amount":1009102.0,"timestamp":1745595567214},{"cardNumber":"1234567812345670","amount":1009102.0,"timestamp":1745595812805},{"cardNumber":"1234567812345670","amount":11.0,"timestamp":1745595869876},{"cardNumber":"1234567812345670","amount":110000.0,"timestamp":1745595939486},{"cardNumber":"1234567812345670","amount":110000.0,"timestamp":1745596107459},{"cardNumber":"1234567812345670","amount":110.0,"timestamp":1745596608417},{"cardNumber":"1234567812345670","amount":22220.0,"timestamp":1745596629599},{"cardNumber":"1234567812345670","amount":22220.0,"timestamp":1745596649335},{"cardNumber":"1234567812345670","amount":2.2E7,"timestamp":1745596862340},{"cardNumber":"1234567812345670","amount":22.0,"timestamp":1745596882101},{"cardNumber":"1234567812345670","amount":22.0,"timestamp":1745940855222},{"cardNumber":"1234567812345670","amount":42500.0,"timestamp":1749300717570},{"cardNumber":"1234567812345670","amount":7000.0,"timestamp":1749005100000},{"cardNumber":"1234567812345670","amount":123456.0,"timestamp":1749302844670},{"cardNumber":"1234567812345670","amount":20000.0,"timestamp":1749307071376},{"cardNumber":"1234567812345670","amount":19999.0,"timestamp":1749307619077},{"cardNumber":"1234567812345670","amount":19998.0,"timestamp":1749307894614}]
2025-06-07 17:09:32.022  INFO 24087 --- [nio-8080-exec-1] com.aciworldwide.aclabs22.services.AnomalyService : JSON input sent to Python script
2025-06-07 17:09:32.040 DEBUG 24087 --- [nio-8080-exec-1] com.aciworldwide.aclabs22.services.AnomalyService : Python output line: [{"cardNumber": "1234567812345670", "amount": 1009102.0, "timestamp": 1745595529759}, {"cardNumber": "1234567812345670", "amount": 1009102.0, "timestamp": 1745595567214}, {"cardNumber": "1234567812345670", "amount": 1009102.0, "timestamp": 1745595812805}, {"cardNumber": "1234567812345670", "amount": 110000.0, "timestamp": 1745595939486}, {"cardNumber": "1234567812345670", "amount": 110000.0, "timestamp": 1745596107459}, {"cardNumber": "1234567812345670", "amount": 22220.0, "timestamp": 1745596629599}, {"cardNumber": "1234567812345670", "amount": 22220.0, "timestamp": 1745596649335}, {"cardNumber": "1234567812345670", "amount": 22000000.0, "timestamp": 1745596862340}, {"cardNumber": "1234567812345670", "amount": 42500.0, "timestamp": 1749300717570}, {"cardNumber": "1234567812345670", "amount": 123456.0, "timestamp": 1749302844670}, {"cardNumber": "1234567812345670", "amount": 20000.0, "timestamp": 1749307071376}, {"cardNumber": "1234567812345670", "amount": 19999.0, "timestamp": 1749307619077}, {"cardNumber": "1234567812345670", "amount": 19998.0, "timestamp": 1749307894614}]
2025-06-07 17:09:32.042  INFO 24087 --- [nio-8080-exec-1] com.aciworldwide.aclabs22.services.AnomalyService : Finished reading output from Python script
2025-06-07 17:09:32.042  INFO 24087 --- [nio-8080-exec-1] com.aciworldwide.aclabs22.services.AnomalyService : Python script exited with code: 0
2025-06-07 17:09:32.049  INFO 24087 --- [nio-8080-exec-1] com.aciworldwide.aclabs22.services.AnomalyService : Anomaly detection returned 13 anomalies
